# Generated by Django 2.0.3 on 2020-06-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='First Project', max_length=200),
            preserve_default=False,
        ),
    ]
